# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:53:23+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    AutopilotV1Assistant,
    AutopilotV1AssistantDefaults,
    AutopilotV1AssistantDialogue,
    AutopilotV1AssistantFieldType,
    AutopilotV1AssistantFieldTypeFieldValue,
    AutopilotV1AssistantModelBuild,
    AutopilotV1AssistantQuery,
    AutopilotV1AssistantStyleSheet,
    AutopilotV1AssistantTask,
    AutopilotV1AssistantTaskField,
    AutopilotV1AssistantTaskSample,
    AutopilotV1AssistantTaskTaskActions,
    AutopilotV1AssistantTaskTaskStatistics,
    AutopilotV1AssistantWebhook,
    AutopilotV1RestoreAssistant,
    V1AssistantsAssistantSidFieldTypesFieldTypeSidFieldValuesGetResponse,
    V1AssistantsAssistantSidFieldTypesGetResponse,
    V1AssistantsAssistantSidModelBuildsGetResponse,
    V1AssistantsAssistantSidQueriesGetResponse,
    V1AssistantsAssistantSidTasksGetResponse,
    V1AssistantsAssistantSidTasksTaskSidFieldsGetResponse,
    V1AssistantsAssistantSidTasksTaskSidSamplesGetResponse,
    V1AssistantsAssistantSidWebhooksGetResponse,
    V1AssistantsGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Autopilot',
    version='1.42.0',
    servers=[{'url': 'https://autopilot.twilio.com'}],
)


@app.get(
    '/v1/Assistants',
    tags=['query_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_assistant(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants',
    tags=['default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_assistant(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/Restore',
    tags=['default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_restore_assistant(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Defaults',
    tags=['assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_defaults(assistant_sid: str = Path(..., alias='AssistantSid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Defaults',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_defaults(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Dialogues/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_dialogue(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/FieldTypes',
    tags=['assistant_management', 'default_settings_management', 'query_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_field_type(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/FieldTypes',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_field_type(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues',
    tags=['field_type_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_field_value(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    field_type_sid: str = Path(..., alias='FieldTypeSid'),
    language: Optional[str] = Query(None, alias='Language'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues',
    tags=['assistant_management', 'field_type_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_field_value(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    field_type_sid: str = Path(..., alias='FieldTypeSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}',
    tags=['assistant_management', 'field_type_operations', 'field_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_field_value(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    field_type_sid: str = Path(..., alias='FieldTypeSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{FieldTypeSid}/FieldValues/{Sid}',
    tags=['assistant_management', 'field_type_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_field_value(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    field_type_sid: str = Path(..., alias='FieldTypeSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_field_type(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_field_type(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/FieldTypes/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_field_type(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/ModelBuilds',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_model_build(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/ModelBuilds',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_model_build(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/ModelBuilds/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_model_build(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/ModelBuilds/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_model_build(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/ModelBuilds/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_model_build(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Queries',
    tags=[
        'assistant_management',
        'default_settings_management',
        'model_build_operations',
        'query_operations',
    ],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_query(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    language: Optional[str] = Query(None, alias='Language'),
    model_build: Optional[str] = Query(None, alias='ModelBuild'),
    status: Optional[str] = Query(None, alias='Status'),
    dialogue_sid: Optional[
        constr(pattern=r'^UK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Query(None, alias='DialogueSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Queries',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_query(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/Queries/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_query(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Queries/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_query(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Queries/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_query(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/StyleSheet',
    description=""" Returns Style sheet JSON object for the Assistant """,
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_style_sheet(assistant_sid: str = Path(..., alias='AssistantSid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/StyleSheet',
    description=""" Updates the style sheet for an Assistant identified by `assistant_sid`. """,
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_style_sheet(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_task(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_task(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/Tasks/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_task(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks/{Sid}',
    tags=['assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions',
    description=""" Returns JSON actions for the Task. """,
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_actions(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Actions',
    description=""" Updates the actions of an Task identified by {TaskSid} or {TaskUniqueName}. """,
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_task_actions(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields',
    tags=['task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_field(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields',
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_field(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}',
    tags=['task_processing', 'assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_field(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Fields/{Sid}',
    tags=['task_processing', 'assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_field(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples',
    tags=['task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_sample(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    language: Optional[str] = Query(None, alias='Language'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples',
    tags=['task_processing', 'assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_sample(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}',
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_sample(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    sid: constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}',
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_sample(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    sid: constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Samples/{Sid}',
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_sample(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
    sid: constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Tasks/{TaskSid}/Statistics',
    tags=['assistant_management', 'task_processing'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_task_statistics(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    task_sid: str = Path(..., alias='TaskSid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Webhooks',
    tags=['assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_webhook(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Webhooks',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_webhook(
    assistant_sid: str = Path(..., alias='AssistantSid'), request: Request = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{AssistantSid}/Webhooks/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_webhook(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{AssistantSid}/Webhooks/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_webhook(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{AssistantSid}/Webhooks/{Sid}',
    tags=['assistant_management', 'default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_webhook(
    assistant_sid: str = Path(..., alias='AssistantSid'),
    sid: str = Path(..., alias='Sid'),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Assistants/{Sid}',
    tags=['default_settings_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_assistant(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Assistants/{Sid}',
    tags=['field_value_operations'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_assistant(sid: str = Path(..., alias='Sid')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Assistants/{Sid}',
    tags=['assistant_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_assistant(sid: str = Path(..., alias='Sid'), request: Request = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
