# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:53:23+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class AutopilotV1Assistant(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Assistant resource.',
    )
    callback_events: Optional[str] = Field(None, description='Reserved.')
    callback_url: Optional[AnyUrl] = Field(None, description='Reserved.')
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    development_stage: Optional[str] = Field(
        None, description='A string describing the state of the assistant.'
    )
    friendly_name: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    latest_model_build_sid: Optional[
        constr(pattern=r'^UG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='Reserved.')
    links: Optional[Dict[str, Any]] = Field(
        None, description="A list of the URLs of the Assistant's related resources."
    )
    log_queries: Optional[bool] = Field(
        None,
        description='Whether queries should be logged and kept after training. Can be: `true` or `false` and defaults to `true`. If `true`, queries are stored for 30 days, and then deleted. If `false`, no queries are stored.',
    )
    needs_model_build: Optional[bool] = Field(
        None, description='Whether model needs to be rebuilt.'
    )
    sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Assistant resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource. It can be up to 64 characters long.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Assistant resource.'
    )


class AutopilotV1AssistantDefaults(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Defaults resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    data: Optional[Any] = Field(
        None,
        description='The JSON string that describes the default task links for the `assistant_initiation`, `collect`, and `fallback` situations.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Defaults resource.'
    )


class AutopilotV1AssistantDialogue(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Dialogue resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    data: Optional[Any] = Field(
        None, description='The JSON string that describes the dialogue session object.'
    )
    sid: Optional[
        constr(pattern=r'^UK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Dialogue resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Dialogue resource.'
    )


class AutopilotV1AssistantFieldType(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the FieldType resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    friendly_name: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='A list of the URLs of related resources.'
    )
    sid: Optional[
        constr(pattern=r'^UB[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the FieldType resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the FieldType resource.'
    )


class AutopilotV1AssistantFieldTypeFieldValue(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the FieldValue resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the FieldType associated with the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    field_type_sid: Optional[
        constr(pattern=r'^UB[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None, description='The SID of the Field Type associated with the Field Value.'
    )
    language: Optional[str] = Field(
        None,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) tag that specifies the language of the value. Currently supported tags: `en-US`',
    )
    sid: Optional[
        constr(pattern=r'^UC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the FieldValue resource.',
    )
    synonym_of: Optional[
        constr(pattern=r'^UC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='The word for which the field value is a synonym of.')
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the FieldValue resource.'
    )
    value: Optional[str] = Field(None, description='The Field Value data.')


class AutopilotV1AssistantQuery(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Query resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    dialogue_sid: Optional[
        constr(pattern=r'^UK[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Dialogue](https://www.twilio.com/docs/autopilot/api/dialogue).',
    )
    language: Optional[str] = Field(
        None,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) string that specifies the language used by the Query. For example: `en-US`.',
    )
    model_build_sid: Optional[
        constr(pattern=r'^UG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Model Build](https://www.twilio.com/docs/autopilot/api/model-build) queried.',
    )
    query: Optional[str] = Field(
        None, description="The end-user's natural language input."
    )
    results: Optional[Any] = Field(
        None,
        description='The natural language analysis results that include the [Task](https://www.twilio.com/docs/autopilot/api/task) recognized and a list of identified [Fields](https://www.twilio.com/docs/autopilot/api/task-field).',
    )
    sample_sid: Optional[
        constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of an optional reference to the [Sample](https://www.twilio.com/docs/autopilot/api/task-sample) created from the query.',
    )
    sid: Optional[
        constr(pattern=r'^UH[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Query resource.',
    )
    source_channel: Optional[str] = Field(
        None,
        description='The communication channel from where the end-user input came.',
    )
    status: Optional[str] = Field(
        None,
        description='The status of the Query. Can be: `pending-review`, `reviewed`, or `discarded`',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Query resource.'
    )


class AutopilotV1AssistantStyleSheet(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the StyleSheet resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    data: Optional[Any] = Field(
        None, description='The JSON string that describes the style sheet object.'
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the StyleSheet resource.'
    )


class AutopilotV1AssistantTask(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Task resource.',
    )
    actions_url: Optional[AnyUrl] = Field(
        None, description='The URL from which the Assistant can fetch actions.'
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    friendly_name: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    links: Optional[Dict[str, Any]] = Field(
        None, description='A list of the URLs of related resources.'
    )
    sid: Optional[
        constr(pattern=r'^UD[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Task resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Task resource.'
    )


class AutopilotV1AssistantTaskField(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Field resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the Task associated with the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    field_type: Optional[str] = Field(
        None,
        description='The Field Type of the field. Can be: a [Built-in Field Type](https://www.twilio.com/docs/autopilot/built-in-field-types), the unique_name, or the SID of a custom Field Type.',
    )
    sid: Optional[
        constr(pattern=r'^UE[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Field resource.',
    )
    task_sid: Optional[
        constr(pattern=r'^UD[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Task](https://www.twilio.com/docs/autopilot/api/task) resource associated with this Field.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Field resource.'
    )


class AutopilotV1AssistantTaskSample(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Sample resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the Task associated with the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    language: Optional[str] = Field(
        None,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) string that specifies the language used for the sample. For example: `en-US`.',
    )
    sid: Optional[
        constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Sample resource.',
    )
    source_channel: Optional[str] = Field(
        None,
        description='The communication channel from which the sample was captured. Can be: `voice`, `sms`, `chat`, `alexa`, `google-assistant`, `slack`, or null if not included.',
    )
    tagged_text: Optional[str] = Field(
        None,
        description='The text example of how end users might express the task. The sample can contain [Field tag blocks](https://www.twilio.com/docs/autopilot/api/task-sample#field-tagging).',
    )
    task_sid: Optional[
        constr(pattern=r'^UD[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Task](https://www.twilio.com/docs/autopilot/api/task) associated with the resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Sample resource.'
    )


class AutopilotV1AssistantTaskTaskActions(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskActions resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the Task associated with the resource.',
    )
    data: Optional[Any] = Field(
        None,
        description='The JSON string that specifies the [actions](https://www.twilio.com/docs/autopilot/actions) that instruct the Assistant on how to perform the task.',
    )
    task_sid: Optional[
        constr(pattern=r'^UD[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Task](https://www.twilio.com/docs/autopilot/api/task) associated with the resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the TaskActions resource.'
    )


class AutopilotV1AssistantTaskTaskStatistics(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskStatistics resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the Task associated with the resource.',
    )
    fields_count: Optional[int] = Field(
        None,
        description='The total number of [Fields](https://www.twilio.com/docs/autopilot/api/task-field) associated with the Task.',
    )
    samples_count: Optional[int] = Field(
        None,
        description='The total number of [Samples](https://www.twilio.com/docs/autopilot/api/task-sample) associated with the Task.',
    )
    task_sid: Optional[
        constr(pattern=r'^UD[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Task](https://www.twilio.com/docs/autopilot/api/task) for which the statistics were collected.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the TaskStatistics resource.'
    )


class AutopilotV1AssistantWebhook(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Webhook resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    events: Optional[str] = Field(
        None,
        description='The list of space-separated events that this Webhook is subscribed to.',
    )
    sid: Optional[
        constr(pattern=r'^UM[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Webhook resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Webhook resource.'
    )
    webhook_method: Optional[str] = Field(
        None, description="The method used when calling the webhook's URL."
    )
    webhook_url: Optional[AnyUrl] = Field(
        None, description='The URL associated with this Webhook.'
    )


class AutopilotV1RestoreAssistant(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Assistant resource.',
    )
    callback_events: Optional[str] = Field(None, description='Reserved.')
    callback_url: Optional[AnyUrl] = Field(None, description='Reserved.')
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    development_stage: Optional[str] = Field(
        None, description='A string describing the state of the assistant.'
    )
    friendly_name: Optional[str] = Field(
        None,
        description='The string that you assigned to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    latest_model_build_sid: Optional[
        constr(pattern=r'^UG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(None, description='Reserved.')
    log_queries: Optional[bool] = Field(
        None,
        description='Whether queries should be logged and kept after training. Can be: `true` or `false` and defaults to `true`. If `true`, queries are stored for 30 days, and then deleted. If `false`, no queries are stored.',
    )
    needs_model_build: Optional[bool] = Field(
        None, description='Whether model needs to be rebuilt.'
    )
    sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Assistant resource.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used in place of the resource's `sid` in the URL to address the resource.",
    )


class ModelBuildEnumStatus(Enum):
    enqueued = 'enqueued'
    building = 'building'
    completed = 'completed'
    failed = 'failed'
    canceled = 'canceled'


class Meta(BaseModel):
    first_page_url: Optional[AnyUrl] = None
    key: Optional[str] = None
    next_page_url: Optional[AnyUrl] = None
    page: Optional[int] = None
    page_size: Optional[int] = None
    previous_page_url: Optional[AnyUrl] = None
    url: Optional[AnyUrl] = None


class V1AssistantsGetResponse(BaseModel):
    assistants: Optional[List[AutopilotV1Assistant]] = None
    meta: Optional[Meta] = None


class V1AssistantsPostRequest(BaseModel):
    CallbackEvents: Optional[str] = Field(None, description='Reserved.')
    CallbackUrl: Optional[AnyUrl] = Field(None, description='Reserved.')
    Defaults: Optional[Any] = Field(
        None,
        description="A JSON object that defines the Assistant's [default tasks](https://www.twilio.com/docs/autopilot/api/assistant/defaults) for various scenarios, including initiation actions and fallback tasks.",
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the new resource. It is not unique and can be up to 255 characters long.',
    )
    LogQueries: Optional[bool] = Field(
        None,
        description='Whether queries should be logged and kept after training. Can be: `true` or `false` and defaults to `true`. If `true`, queries are stored for 30 days, and then deleted. If `false`, no queries are stored.',
    )
    StyleSheet: Optional[Any] = Field(
        None,
        description="The JSON string that defines the Assistant's [style sheet](https://www.twilio.com/docs/autopilot/api/assistant/stylesheet)",
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the new resource. It can be used as an alternative to the `sid` in the URL path to address the resource. The first 64 characters must be unique.',
    )


class V1AssistantsRestorePostRequest(BaseModel):
    Assistant: str = Field(
        ...,
        description='The Twilio-provided string that uniquely identifies the Assistant resource to restore.',
    )


class V1AssistantsAssistantSidDefaultsPostRequest(BaseModel):
    Defaults: Optional[Any] = Field(
        None,
        description='A JSON string that describes the default task links for the `assistant_initiation`, `collect`, and `fallback` situations.',
    )


class V1AssistantsAssistantSidFieldTypesGetResponse(BaseModel):
    field_types: Optional[List[AutopilotV1AssistantFieldType]] = None
    meta: Optional[Meta] = None


class V1AssistantsAssistantSidFieldTypesPostRequest(BaseModel):
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the new resource. It is not unique and can be up to 255 characters long.',
    )
    UniqueName: str = Field(
        ...,
        description='An application-defined string that uniquely identifies the new resource. It can be used as an alternative to the `sid` in the URL path to address the resource. The first 64 characters must be unique.',
    )


class V1AssistantsAssistantSidFieldTypesFieldTypeSidFieldValuesGetResponse(BaseModel):
    field_values: Optional[List[AutopilotV1AssistantFieldTypeFieldValue]] = None
    meta: Optional[Meta] = None


class V1AssistantsAssistantSidFieldTypesFieldTypeSidFieldValuesPostRequest(BaseModel):
    Language: str = Field(
        ...,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) tag that specifies the language of the value. Currently supported tags: `en-US`',
    )
    SynonymOf: Optional[str] = Field(
        None,
        description='The string value that indicates which word the field value is a synonym of.',
    )
    Value: str = Field(..., description='The Field Value data.')


class V1AssistantsAssistantSidFieldTypesSidPostRequest(BaseModel):
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. It can be used as an alternative to the `sid` in the URL path to address the resource. The first 64 characters must be unique.',
    )


class V1AssistantsAssistantSidModelBuildsPostRequest(BaseModel):
    StatusCallback: Optional[AnyUrl] = Field(
        None,
        description='The URL we should call using a POST method to send status information to your application.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the new resource. This value must be a unique string of no more than 64 characters. It can be used as an alternative to the `sid` in the URL path to address the resource.',
    )


class V1AssistantsAssistantSidModelBuildsSidPostRequest(BaseModel):
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be a unique string of no more than 64 characters. It can be used as an alternative to the `sid` in the URL path to address the resource.',
    )


class V1AssistantsAssistantSidQueriesGetResponse(BaseModel):
    meta: Optional[Meta] = None
    queries: Optional[List[AutopilotV1AssistantQuery]] = None


class V1AssistantsAssistantSidQueriesPostRequest(BaseModel):
    Language: str = Field(
        ...,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) string that specifies the language used for the new query. For example: `en-US`.',
    )
    ModelBuild: Optional[str] = Field(
        None,
        description='The SID or unique name of the [Model Build](https://www.twilio.com/docs/autopilot/api/model-build) to be queried.',
    )
    Query: str = Field(
        ...,
        description="The end-user's natural language input. It can be up to 2048 characters long.",
    )
    Tasks: Optional[str] = Field(
        None,
        description='The list of tasks to limit the new query to. Tasks are expressed as a comma-separated list of task `unique_name` values. For example, `task-unique_name-1, task-unique_name-2`. Listing specific tasks is useful to constrain the paths that a user can take.',
    )


class V1AssistantsAssistantSidQueriesSidPostRequest(BaseModel):
    SampleSid: Optional[
        constr(pattern=r'^UF[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of an optional reference to the [Sample](https://www.twilio.com/docs/autopilot/api/task-sample) created from the query.',
    )
    Status: Optional[str] = Field(
        None,
        description='The new status of the resource. Can be: `pending-review`, `reviewed`, or `discarded`',
    )


class V1AssistantsAssistantSidStyleSheetPostRequest(BaseModel):
    StyleSheet: Optional[Any] = Field(
        None, description='The JSON string that describes the style sheet object.'
    )


class V1AssistantsAssistantSidTasksGetResponse(BaseModel):
    meta: Optional[Meta] = None
    tasks: Optional[List[AutopilotV1AssistantTask]] = None


class V1AssistantsAssistantSidTasksPostRequest(BaseModel):
    Actions: Optional[Any] = Field(
        None,
        description='The JSON string that specifies the [actions](https://www.twilio.com/docs/autopilot/actions) that instruct the Assistant on how to perform the task. It is optional and not unique.',
    )
    ActionsUrl: Optional[AnyUrl] = Field(
        None, description='The URL from which the Assistant can fetch actions.'
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the new resource. It is not unique and can be up to 255 characters long.',
    )
    UniqueName: str = Field(
        ...,
        description='An application-defined string that uniquely identifies the new resource. It can be used as an alternative to the `sid` in the URL path to address the resource. This value must be unique and 64 characters or less in length.',
    )


class V1AssistantsAssistantSidTasksSidPostRequest(BaseModel):
    Actions: Optional[Any] = Field(
        None,
        description='The JSON string that specifies the [actions](https://www.twilio.com/docs/autopilot/actions) that instruct the Assistant on how to perform the task.',
    )
    ActionsUrl: Optional[AnyUrl] = Field(
        None, description='The URL from which the Assistant can fetch actions.'
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. This value must be 64 characters or less in length and be unique. It can be used as an alternative to the `sid` in the URL path to address the resource.',
    )


class V1AssistantsAssistantSidTasksTaskSidActionsPostRequest(BaseModel):
    Actions: Optional[Any] = Field(
        None,
        description='The JSON string that specifies the [actions](https://www.twilio.com/docs/autopilot/actions) that instruct the Assistant on how to perform the task.',
    )


class V1AssistantsAssistantSidTasksTaskSidFieldsGetResponse(BaseModel):
    fields: Optional[List[AutopilotV1AssistantTaskField]] = None
    meta: Optional[Meta] = None


class V1AssistantsAssistantSidTasksTaskSidFieldsPostRequest(BaseModel):
    FieldType: str = Field(
        ...,
        description='The Field Type of the new field. Can be: a [Built-in Field Type](https://www.twilio.com/docs/autopilot/built-in-field-types), the `unique_name`, or the `sid` of a custom Field Type.',
    )
    UniqueName: str = Field(
        ...,
        description='An application-defined string that uniquely identifies the new resource. This value must be a unique string of no more than 64 characters. It can be used as an alternative to the `sid` in the URL path to address the resource.',
    )


class V1AssistantsAssistantSidTasksTaskSidSamplesGetResponse(BaseModel):
    meta: Optional[Meta] = None
    samples: Optional[List[AutopilotV1AssistantTaskSample]] = None


class V1AssistantsAssistantSidTasksTaskSidSamplesPostRequest(BaseModel):
    Language: str = Field(
        ...,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) string that specifies the language used for the new sample. For example: `en-US`.',
    )
    SourceChannel: Optional[str] = Field(
        None,
        description='The communication channel from which the new sample was captured. Can be: `voice`, `sms`, `chat`, `alexa`, `google-assistant`, `slack`, or null if not included.',
    )
    TaggedText: str = Field(
        ...,
        description='The text example of how end users might express the task. The sample can contain [Field tag blocks](https://www.twilio.com/docs/autopilot/api/task-sample#field-tagging).',
    )


class V1AssistantsAssistantSidTasksTaskSidSamplesSidPostRequest(BaseModel):
    Language: Optional[str] = Field(
        None,
        description='The [ISO language-country](https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html) string that specifies the language used for the sample. For example: `en-US`.',
    )
    SourceChannel: Optional[str] = Field(
        None,
        description='The communication channel from which the sample was captured. Can be: `voice`, `sms`, `chat`, `alexa`, `google-assistant`, `slack`, or null if not included.',
    )
    TaggedText: Optional[str] = Field(
        None,
        description='The text example of how end users might express the task. The sample can contain [Field tag blocks](https://www.twilio.com/docs/autopilot/api/task-sample#field-tagging).',
    )


class V1AssistantsAssistantSidWebhooksGetResponse(BaseModel):
    meta: Optional[Meta] = None
    webhooks: Optional[List[AutopilotV1AssistantWebhook]] = None


class V1AssistantsAssistantSidWebhooksPostRequest(BaseModel):
    Events: str = Field(
        ...,
        description='The list of space-separated events that this Webhook will subscribe to.',
    )
    UniqueName: str = Field(
        ...,
        description='An application-defined string that uniquely identifies the new resource. It can be used as an alternative to the `sid` in the URL path to address the resource. This value must be unique and 64 characters or less in length.',
    )
    WebhookMethod: Optional[str] = Field(
        None, description="The method to be used when calling the webhook's URL."
    )
    WebhookUrl: AnyUrl = Field(..., description='The URL associated with this Webhook.')


class V1AssistantsAssistantSidWebhooksSidPostRequest(BaseModel):
    Events: Optional[str] = Field(
        None,
        description='The list of space-separated events that this Webhook will subscribe to.',
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the new resource. It can be used as an alternative to the `sid` in the URL path to address the resource. This value must be unique and 64 characters or less in length.',
    )
    WebhookMethod: Optional[str] = Field(
        None, description="The method to be used when calling the webhook's URL."
    )
    WebhookUrl: Optional[AnyUrl] = Field(
        None, description='The URL associated with this Webhook.'
    )


class V1AssistantsSidPostRequest(BaseModel):
    CallbackEvents: Optional[str] = Field(None, description='Reserved.')
    CallbackUrl: Optional[AnyUrl] = Field(None, description='Reserved.')
    Defaults: Optional[Any] = Field(
        None,
        description="A JSON object that defines the Assistant's [default tasks](https://www.twilio.com/docs/autopilot/api/assistant/defaults) for various scenarios, including initiation actions and fallback tasks.",
    )
    DevelopmentStage: Optional[str] = Field(
        None, description='A string describing the state of the assistant.'
    )
    FriendlyName: Optional[str] = Field(
        None,
        description='A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.',
    )
    LogQueries: Optional[bool] = Field(
        None,
        description='Whether queries should be logged and kept after training. Can be: `true` or `false` and defaults to `true`. If `true`, queries are stored for 30 days, and then deleted. If `false`, no queries are stored.',
    )
    StyleSheet: Optional[Any] = Field(
        None,
        description="The JSON string that defines the Assistant's [style sheet](https://www.twilio.com/docs/autopilot/api/assistant/stylesheet)",
    )
    UniqueName: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. It can be used as an alternative to the `sid` in the URL path to address the resource. The first 64 characters must be unique.',
    )


class AutopilotV1AssistantModelBuild(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ModelBuild resource.',
    )
    assistant_sid: Optional[
        constr(pattern=r'^UA[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Assistant](https://www.twilio.com/docs/autopilot/api/assistant) that is the parent of the resource.',
    )
    build_duration: Optional[int] = Field(
        None, description='The time in seconds it took to build the model.'
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.',
    )
    error_code: Optional[int] = Field(
        None,
        description='If the `status` for the model build is `failed`, this value is a code to more information about the failure. This value will be null for all other statuses. See [error code dictionary](https://www.twilio.com/docs/api/errors) for a description of the error.',
    )
    sid: Optional[
        constr(pattern=r'^UG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the ModelBuild resource.',
    )
    status: Optional[ModelBuildEnumStatus] = Field(
        None,
        description='The status of the model build process. Can be: `enqueued`, `building`, `completed`, or `failed`',
    )
    unique_name: Optional[str] = Field(
        None,
        description='An application-defined string that uniquely identifies the resource. It can be used as an alternative to the `sid` in the URL path to address the resource.',
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the ModelBuild resource.'
    )


class V1AssistantsAssistantSidModelBuildsGetResponse(BaseModel):
    meta: Optional[Meta] = None
    model_builds: Optional[List[AutopilotV1AssistantModelBuild]] = None
